enum MessageType {
  START_AUTH = "START_AUTH",
  REGISTER_TOKEN = "REGISTER_TOKEN",
  RELOAD_CREDITS_LIMIT = "RELOAD_CREDITS_LIMIT",
  GET_COMMENT = "GET_COMMENT",
  GET_PROMPTS = "GET_PROMPTS",
  DELETE_PROMPT = "DELETE_PROMPT",
  UPDATE_PROMPT = "UPDATE_PROMPT",
  SAVE_PROMPT = "SAVE_PROMPT",
  SEND_FEEDBACK = "SEND_FEEDBACK",

  GET_PLANS = "GET_PLANS",
  CONFIRM_PAYMENT = "CONFIRM_PAYMENT",
  GET_SUBSCRIPTION_URL = "GET_SUBSCRIPTION_URL",
  DISABLE_PROMPT = "DISABLE_PROMPT",
  DISABLE_DEFAULT_PROMPT = "DISABLE_DEFAULT_PROMPT",
}
export default MessageType;
